DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS chats;
DROP TABLE IF EXISTS messages;

CREATE TABLE user (
  userid INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE chats (
  chatid INTEGER PRIMARY KEY AUTOINCREMENT,
  users TEXT NOT NULL,
  chatname TEXT NOT NULL,
  iconpath TEXT,
  messages TEXT NOT NULL
);
